version: '3.0'
services: 
  api:
    build: ./LesSaveursDeFatma_BackSide/  
    container_name: api
    ports:
      - "3000:3000"
      - "9000:9000" 
    expose:
      - "3000"
    command : npm start
    environment:
       URL: mongodb://db:27017/saveursDeFatma
       SECRETKEY: secret
    volumes:
      - ./LesSaveursDeFatma_BackSide/:/app  
      - /app/node_modules
    links:
      - db
    
  web:
    build: ./LesSaveursDeFatma_FrontSide/
    container_name: web
    ports:
      - "4300:80" 
    volumes:
      - ./LesSaveursDeFatma_FrontSide/:/app
      - /app/node_modules

  db:
    image: mongo  #image officielle de mongo
    container_name: db
    restart: always
    volumes:
      - data:/data/db  # Utilisez un volume nommé "data" pour stocker les données de MongoDB
    ports: 
      - "27017:27017"
  nginx:
    build: ./nginx/
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    links:
      - api
      - web
#le volume nous permet de stocker ses données en dehors du conteneur lui-même
volumes:
  data: 